# Tensorflow: Practice

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


In [4]:
# Loading MNIST dataset (handwritten digits)

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
# Building a simple sequential model
# Model contains flatten, dense, and dropout layers

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
# The model results in logits scores

predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.85750765, -0.50015265,  0.5329328 , -0.08741084, -0.07643667,
         0.10446022, -0.16884439, -0.16535117,  0.01493779, -0.08445308]],
      dtype=float32)

In [8]:
# Softmax converts the logits to predictions

tf.nn.softmax(predictions).numpy()

array([[0.20959614, 0.05392113, 0.15150334, 0.08147238, 0.0823714 ,
        0.09870496, 0.07510075, 0.07536355, 0.09025264, 0.08171372]],
      dtype=float32)

In [9]:
# Creating a loss function 

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
# Untrainined model should give probabilities close to random (1/10)

loss_fn(y_train[:1], predictions).numpy()

2.3156202

In [12]:
# Compiling the model before training

model.compile(optimizer='adam', # Setting optimizer to adam
              loss=loss_fn, # Setting loss to pre-defined loss function
              metrics=['accuracy']) # Setting metrics to accuracy

In [13]:
# Training model

model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-09-10 10:34:39.134100: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8494 - loss: 0.4995
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9535 - loss: 0.1578
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9669 - loss: 0.1105
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9735 - loss: 0.0863
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9756 - loss: 0.0738


In [14]:
# Evaluating the model

model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9774 - loss: 0.0718


[0.07179126143455505, 0.977400004863739]

In [15]:
# Returning probability by wrapping and attaching softmax to the trained model

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.9747458e-08, 4.4641153e-09, 4.0508726e-06, 1.4259215e-04,
        8.7995572e-10, 6.7892125e-07, 8.9497171e-13, 9.9984455e-01,
        8.7868536e-08, 7.9960437e-06],
       [8.6632843e-09, 4.8875445e-05, 9.9989581e-01, 8.7343578e-06,
        6.6279007e-14, 5.0436250e-07, 2.5001918e-07, 4.0960972e-12,
        4.5782275e-05, 1.5204607e-14],
       [6.0731730e-07, 9.9751991e-01, 2.5221001e-04, 1.5131574e-05,
        1.3540483e-04, 3.2127055e-06, 2.9650777e-05, 1.6435503e-03,
        3.9891605e-04, 1.2491362e-06],
       [9.9904221e-01, 1.0670141e-08, 2.5265079e-04, 3.7495122e-06,
        2.4328256e-06, 7.7830600e-06, 5.8731640e-04, 4.9567323e-05,
        3.2241940e-06, 5.1078565e-05],
       [9.3462377e-06, 1.0847461e-09, 2.3409777e-06, 1.3367905e-08,
        9.9857056e-01, 2.0219952e-07, 2.8924203e-06, 6.7751548e-06,
        1.1902903e-06, 1.4066512e-03]], dtype=float32)>