# Tensorflow: Practice

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Users/belierjavier/Desktop/Research/CSC390-ML-Research/.venv/lib/python3.9/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2024-09-09 13:07:13.896288: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2024-09-09 13:07:13.896324: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-09-09 13:07:13.896338: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-09-09 13:07:13.896546: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-09 13:07:13.896563: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created Te

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.47448522,  0.32531685,  0.10008617, -0.63508713, -0.43487123,
        -0.6193732 ,  0.06674001,  0.10228384, -0.16617033,  0.07693928]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.06966762, 0.15501747, 0.1237554 , 0.05933111, 0.07248282,
        0.0602708 , 0.11969668, 0.12402768, 0.09482665, 0.12092375]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.8089075

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-09-09 13:08:32.346304: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8579 - loss: 0.4849
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9557 - loss: 0.1506
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9679 - loss: 0.1056
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9724 - loss: 0.0894
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9776 - loss: 0.0756


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9765 - loss: 0.0749


[0.07492367923259735, 0.9764999747276306]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.9277739e-10, 2.2531335e-10, 1.1119062e-06, 7.2042340e-06,
        6.5076720e-13, 5.1162576e-09, 1.0678577e-13, 9.9999106e-01,
        9.5442957e-08, 5.6905645e-07],
       [6.9186136e-08, 1.4528846e-05, 9.9998295e-01, 1.3292040e-06,
        2.0037039e-16, 5.5264593e-07, 1.8897948e-09, 5.5521506e-16,
        4.9899086e-07, 1.6135391e-15],
       [9.8289767e-08, 9.9923110e-01, 1.4816276e-04, 2.2913397e-05,
        1.7556906e-05, 1.0474517e-06, 1.2658192e-05, 4.6957098e-04,
        9.6679447e-05, 2.4031934e-07],
       [9.9990737e-01, 4.2454045e-09, 8.2554925e-06, 8.5251884e-08,
        1.1796684e-06, 6.3567448e-08, 6.3941479e-05, 1.8145922e-05,
        2.4800201e-08, 8.5174713e-07],
       [2.5239888e-05, 1.2760553e-09, 9.5935493e-06, 1.2000933e-08,
        9.9890172e-01, 4.4590175e-07, 1.4935724e-05, 2.2825717e-04,
        3.0442271e-07, 8.1938802e-04]], dtype=float32)>